format_version: 2
pipelines:
  leafletImageOverlay:
    group: PyFarm
    label_template: ${COUNT}
    lock_behavior: none
    mingle:
      base_url: https://pyfarm.mingle.thoughtworks.com
      project_identifier: pyfarm
      mql_grouping_conditions: "status > 'In Dev'"
    materials:
      leafletImageOverlay:
        git: git@github.com:biqmind/Leaflet.ImageOverlay.Rotated.git
        branch: gh-pages
    stages:
      - CNPMPublishJob:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            CNPMPublish:
              resources:
                - rhel-agent
              tasks:
                - exec:
                    run_if: passed
                    command: yarn
                - exec:
                    run_if: passed
                    command: cnpm
                    arguments:
                      - publish

